### PR TITLE
gasliquid calculation seperated out to seperate model file

### PR DESCRIPTION
**Pull request by TrystanLea**

### CODE REVIEW

**Comment by TrystanLea** [comment]
just sorting the merge conflicts almost there

**Comment by TrystanLea** [comment]
conflicts fixed

**Comment by philJam** [comment]
Looks good apart from lost some of the store results e.g. max discharge etc.

**Comment by philJam** [comment]
A few more issues to log...
Hydrogen needs correcting - have to make sure conversion is correct between TWh and GWh
Option for not using H2 for synth. fuels needs putting in
H2 shortfall (and possibly biomass shortfall) are useful to report

Suggest we work on the modularized one for a bit then check it before putting it live on the website.

**Comment by TrystanLea** [comment]
Thanks Phil, after trying it Im not 100% convinced yet that this modularization idea is going to work, there are a lot of variables we are using for the UI that are in the global space and it gets difficult quite quickly, it may be possible to rearrange each model "block" like this to make this work:

```
var elecstore = {
    SOC: 0,
    statistic_variables...

    reset: function() {
        // reset stats at beginning of run
    }

    run: function(balance) {
        // run elecstore iteration
        return elecstore_charge_discharge;
    }
}
```

but im not sure if that starts to over complicate things. Perhaps its better to just clearly define blocks in one long model file with comment seperation like:

```
// ---------------------------------------------------------------------------------------------
// Elecstore
// ---------------------------------------------------------------------------------------------
// Inputs to the elecstore block are: ....
```

not sure...

Anyway also thinking about the section on producing sythetic fuel and gas, to use synthetic gas for backup generation i guess we need to move the code into the main loop and introduce a store. thinking through the order of calculation, is there anything I have missed here?

Hydrogen
1. Exess electricity produces hydrogen at hydrogen production capacity, hydrogen is stored in a hydrogen store.
2. Direct hydrogen demands and subtracted from the hydrogen store.

Synthetic liquid fuel:
3. Synthetic fuel is produced first from available hydrogen and biomass, limited by the synthetic fuel production capacity and synthetic fuel store which are sized to supply the demand.
4. Synthetic fuel demand is subtracted from the store.
5. If there is not enough synthetic fuel in the store then produce for that demand directly using less efficient direct method.

Synthetic gas:
6. Exess hydrogen and biomass is then used to produce biomethane using sabatier process, limited by sabatier production capacity and methane store capacity
7. Synthetic gas demands are subtracted from store including demand for backup generation.
8. If there is not enough synthetic gas, gas is produced using less efficient direct method.

I will have a go at getting this to work

**Comment by philJam** [comment]
Yes, happy to go with one long clearly separated code if you think that best.

I think the synthetic fuels description below seems ok but I wonder if just reproducing the TYHME spreadsheet model is the way to go. 
That works ok if the H2 & biomass supply is sufficient but we want our model to deal equally well with cases when they are not. 
I can see that optimal use of biomass needs considering i.e. don't just meet demand in every hour, meet the aggregate annual demand in most biomass efficient way (although this raises the interesting question of to what extent you allow the model to have 'foresight', real systems of some but not perfect foresight, and this issue applies in other areas too such as meeting demand for industrial production). 
Also if we introduce a liquid synth fuels production capacity then that needs to work so it can overproduce at some times and underproduce at others without direct biofuel production kicking in. 
I don't think liquid fuels storage is really an issue, so i'm not sure we need to model that as a constraint. To some extent gas storage, and even more so hydrogen storage are real world constraints so probably is good to model those.

I also wonder, can we write it in a way that allows either gas or liquid to be prioritised, or for production to be split between them?

Exciting about Tom Counsell's interest!!

Date: Fri, 23 Jan 2015 01:57:53 -0800

**Pull request merged**
